name: The Static Frost
favicon: null
layout_spectrum: 0
typography_spectrum: 0.82828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030406'
    - '#8ba6d5'
    - '#31415b'
    - '#0fb7f4'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
